import Foundation

// MARK: - Settings Keys

extension AppSettingsStore {
    enum Keys {
        static let aiConfiguration = "aiConfiguration"
        static let enhancementsAISelection = "enhancementsAISelection"
        static let enhancementsDictationAISelection = "enhancementsDictationAISelection"
        static let enhancementsProviderSelectedModels = "enhancementsProviderSelectedModels"
        static let enhancementsProviderRegistrations = "enhancementsProviderRegistrations"
        static let enhancementsProviderSelectedModelsByRegistration = "enhancementsProviderSelectedModelsByRegistration"
        static let transcriptionDictationSelection = "transcriptionDictationSelection"
        static let transcriptionProviderSelectedModels = "transcriptionProviderSelectedModels"
        static let meetingTranscriptionLocalModel = "meetingTranscriptionLocalModel"
        static let systemPrompt = "postProcessingSystemPrompt"
        static let userPrompts = "postProcessingUserPrompts"
        static let selectedPromptId = "postProcessingSelectedPromptId"
        static let dictationPrompts = "dictationPrompts"
        static let dictationSelectedPromptId = "dictationSelectedPromptId"
        static let postProcessingEnabled = "postProcessingEnabled"
        static let dictationStructuredPostProcessingEnabled = "dictationStructuredPostProcessingEnabled"
        static let isDiarizationEnabled = "isDiarizationEnabled"
        static let modelResidencyTimeout = "modelResidencyTimeout"
        static let isMeetingTranscriptionEnabled = "isMeetingTranscriptionEnabled"
        static let isAssistantIntegrationsEnabled = "isAssistantIntegrationsEnabled"
        static let transcriptionInputLanguageHint = "transcriptionInputLanguageHint"
        static let minSpeakers = "minSpeakers"
        static let maxSpeakers = "maxSpeakers"
        static let numSpeakers = "numSpeakers"
        static let selectedLanguage = "selectedLanguage"
        static let audioDevicePriority = "audioDevicePriority"
        static let useSystemDefaultInput = "useSystemDefaultInput"
        static let microphoneWhenChargingUID = "microphoneWhenChargingUID"
        static let microphoneOnBatteryUID = "microphoneOnBatteryUID"
        static let recordingMediaHandlingMode = "recordingMediaHandlingMode"
        static let audioDuckingEnabled = "audioDuckingEnabled"
        static let audioDuckingLevelPercent = "audioDuckingLevelPercent"
        // Legacy key kept only for one-time migration into Audio Ducking settings.
        static let muteOutputDuringRecording = "muteOutputDuringRecording"
        static let autoIncreaseMicrophoneVolume = "autoIncreaseMicrophoneVolume"
        static let removeSilenceBeforeProcessing = "removeSilenceBeforeProcessing"
        static let deletedPromptIds = "postProcessingDeletedPromptIds"
        static let shortcutActivationMode = "shortcutActivationMode"
        static let dictationShortcutActivationMode = "dictationShortcutActivationMode"
        static let shortcutDoubleTapIntervalMilliseconds = "shortcutDoubleTapIntervalMilliseconds"
        static let useEscapeToCancelRecording = "useEscapeToCancelRecording"
        static let selectedPresetKey = "selectedPresetKey"
        static let dictationSelectedPresetKey = "dictationSelectedPresetKey"
        static let meetingSelectedPresetKey = "meetingSelectedPresetKey"
        static let dictationShortcutDefinition = "dictationShortcutDefinition"
        static let assistantShortcutDefinition = "assistantShortcutDefinition"
        static let meetingShortcutDefinition = "meetingShortcutDefinition"
        static let cancelRecordingShortcutDefinition = "cancelRecordingShortcutDefinition"
        static let dictationModifierShortcutGesture = "dictationModifierShortcutGesture"
        static let assistantModifierShortcutGesture = "assistantModifierShortcutGesture"
        static let meetingModifierShortcutGesture = "meetingModifierShortcutGesture"
        static let assistantShortcutActivationMode = "assistantShortcutActivationMode"
        static let assistantUseEscapeToCancelRecording = "assistantUseEscapeToCancelRecording"
        static let assistantUseEnterToStopRecording = "assistantUseEnterToStopRecording"
        static let assistantSelectedPresetKey = "assistantSelectedPresetKey"
        static let assistantBorderColor = "assistantBorderColor"
        static let assistantBorderStyle = "assistantBorderStyle"
        static let assistantBorderWidth = "assistantBorderWidth"
        static let assistantGlowSize = "assistantGlowSize"
        static let assistantIntegrations = "assistantIntegrations"
        static let assistantSelectedIntegrationId = "assistantSelectedIntegrationId"
        static let assistantRaycastEnabled = "assistantRaycastEnabled"
        static let assistantRaycastDeepLink = "assistantRaycastDeepLink"
        static let recordingIndicatorEnabled = "recordingIndicatorEnabled"
        static let recordingIndicatorStyle = "recordingIndicatorStyle"
        static let recordingIndicatorPosition = "recordingIndicatorPosition"
        static let recordingIndicatorAnimationSpeed = "recordingIndicatorAnimationSpeed"
        static let autoDeleteTranscriptions = "autoDeleteTranscriptions"
        static let autoDeletePeriodDays = "autoDeletePeriodDays"
        static let appAccentColor = "appAccentColor"
        // Sound Feedback
        static let soundFeedbackEnabled = "soundFeedbackEnabled"
        static let recordingStartSound = "recordingStartSound"
        static let recordingStopSound = "recordingStopSound"
        /// App Visibility
        static let showInDock = "showInDock"

        // MARK: - Meeting Summary Configuration

        static let meetingTypeAutoDetectEnabled = "meetingTypeAutoDetectEnabled"
        static let meetingSummaryOutputLanguage = "meetingSummaryOutputLanguage"
        static let meetingPrompts = "meetingPrompts"
        static let summaryExportFolder = "summaryExportFolder"
        static let summaryTemplate = "summaryTemplate"
        static let summaryTemplateEnabled = "summaryTemplateEnabled"
        static let autoExportSummaries = "autoExportSummaries"
        static let summaryExportSafetyPolicyLevel = "summaryExportSafetyPolicyLevel"
        static let meetingNotesFontFamilyKey = "meetingNotesFontFamilyKey"
        static let meetingNotesFontSize = "meetingNotesFontSize"
        static let ignoredCalendarEventIdentifiers = "ignoredCalendarEventIdentifiers"
        static let meetingQnAEnabled = "meetingQnAEnabled"
        static let contextAwarenessEnabled = "contextAwarenessEnabled"
        static let contextAwarenessIncludeClipboard = "contextAwarenessIncludeClipboard"
        static let contextAwarenessIncludeWindowOCR = "contextAwarenessIncludeWindowOCR"
        static let contextAwarenessIncludeAccessibilityText = "contextAwarenessIncludeAccessibilityText"
        static let contextAwarenessProtectSensitiveApps = "contextAwarenessProtectSensitiveApps"
        static let contextAwarenessRedactSensitiveData = "contextAwarenessRedactSensitiveData"
        static let contextAwarenessExcludedBundleIDs = "contextAwarenessExcludedBundleIDs"
        static let markdownTargetBundleIdentifiers = "markdownTargetBundleIdentifiers"
        static let dictationAppRules = "dictationAppRules"
        static let dictationStyles = "dictationStyles"
        static let vocabularyReplacementRules = "vocabularyReplacementRules"
        static let markdownWebTargets = "markdownWebTargets"
        static let webTargetBrowserBundleIdentifiers = "webTargetBrowserBundleIdentifiers"
        static let monitoredMeetingBundleIdentifiers = "monitoredMeetingBundleIdentifiers"
        static let webMeetingTargets = "webMeetingTargets"
        static let hasCompletedOnboarding = "hasCompletedOnboarding"
        static let smartSpacingAndCapitalizationEnabled = "smartSpacingAndCapitalizationEnabled"
        static let smartParagraphsEnabled = "smartParagraphsEnabled"
    }
}
